spring:
  server:
    max-http-header-size: 20000
  datasource:
    url: jdbc:mysql://172.27.0.2:3306/flights
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        ddl-auto: update
        column_ordering_strategy: legacy
    generate-ddl: true
server:
  port: 8082
  max-http-size: 2000

keys:
  ati_api_key: b7c4853abe70fe0b85fb700b1abcc8a1d00bf0af142bfe0a19c0bb547e7c1c27

rsa:
  private-key: classpath:certs/private-key.pem
  public-key: classpath:certs/public-key.pem
